name: 'Gear tech fork action.'
description: 'Fork checks from workflow run.'

inputs:
  token:
    description: 'The github token to trigger this action.'
    required: true
  workflow_id:
    description: 'The ID of the target workflow.'
    required: true
  jobs:
    description: 'The jobs to be forked from the jobs of target workflow.'
    required: true
  # repo:
  #   description: 'The full name of the github repo.'
  #   required: true
  #   default: 'gear-tech/gear'
  # ref:
  #   description: 'The git reference of the target workflow.'
  #   required: true
  #   default: 'master'
  # head_sha:
  #   description: 'The target commit that creates checks on.'
  #   required: true
  inputs:
    description: 'The inputs of the target workflow'
    required: true
    default: '{}'
  prefix:
    description: 'The prefix of the check'
    required: true
    default: ''
  release:
    description: 'If enable release build'
    default: false
  production:
    description: 'If enable production build'
    default: false
  profiles:
    description: 'If generate profiles'
    default: false
  multi:
    description: 'If enable multi build fields'
    default: false

runs:
  using: node20
  main: dist/index.js
