name: 'Gear tech fork action.'
description: 'Fork checks from workflow run.'

inputs:
  workflow_id:
    description: 'The ID of the target workflow.'
    required: true
  jobs:
    description: 'The jobs to be forked from the jobs of target workflow.'
    required: true
  head_sha:
    description: 'The target commit that creates checks on.'
    required: true
  repo:
    description: 'The full name of the github repo.'
    required: true
    default: 'gear-tech/gear'
  ref:
    description: 'The git reference of the target workflow.'
    required: true
    default: 'master'
  token:
    description: 'The github token to trigger this action.'
    default: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: node18
  main: dist/index.js
