name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install current dependencies
        run: yarn install --frozen-lockfile

      - name: Check Format
        run: yarn format:check

      - name: Lint
        run: yarn lint

  fork-running:
    name: fork-running
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Fork running workflow
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: '.github/workflows/check-dist.yml'
          jobs: '["Check dist"]'
          head_sha: ${{ github.event.pull_request.head.sha }}
          repo: 'gear-tech/fork-action'
          ref: ${{ github.head_ref || github.ref_name }}

  dispatch-and-fork:
    name: dispatch-and-fork
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Dispatch and Fork
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: '.github/workflows/dispatch.yml'
          jobs: '["dispatch"]'
          head_sha: ${{ github.event.pull_request.head.sha }}
          repo: 'gear-tech/fork-action'
          ref: ${{ github.head_ref || github.ref_name }}
          prefix: 'build / '
          inputs:
            '{ "title": "${{ github.event.pull_request.title }}", "number": ${{
            github.event.number }} }'
