name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install current dependencies
        run: yarn install --frozen-lockfile

      - name: Check Format
        run: yarn format:check

      - name: Lint
        run: yarn lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    if: github.event_name == "pull_request"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: '.github/workflows/check-dist.yml'
          jobs: ['Diff']
          head_sha: ${{ github.event.pull_request.head.sha }}
          repo: 'gear-tech/fork-action'
          ref: ${{ github.head_ref || github.ref_name }}
