name: Dispatch

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        description: 'Pull request title that triggers this workflow.'
      number:
        type: string
        description: 'Pull request number that triggers this workflow'
  pull_request:

run-name: ${{ inputs.title }} ( ${{ format('#{0}', inputs.number) }} )

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: echo "Hello, world"
